"""empty message

Revision ID: 02282dbd5252
Revises: 67d754147c3c
Create Date: 2025-02-21 21:31:22.943871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02282dbd5252'
down_revision = '67d754147c3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temperature', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('voltage', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.drop_column('voltage')
        batch_op.drop_column('temperature')

    # ### end Alembic commands ###
