"""added flag for discharge

Revision ID: 14fc6f765884
Revises: 864cafd49d68
Create Date: 2025-04-04 14:10:59.324074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14fc6f765884'
down_revision = '864cafd49d68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discharge_started', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.drop_column('discharge_started')

    # ### end Alembic commands ###
