"""Fixed Simulation Model

Revision ID: 2d48341e5d76
Revises: 3d6703043d05
Create Date: 2024-11-19 16:11:57.417604

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2d48341e5d76'
down_revision = '3d6703043d05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulation_results', schema=None) as batch_op:
        batch_op.alter_column('vibration_level',
               existing_type=mysql.VARCHAR(length=2),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulation_results', schema=None) as batch_op:
        batch_op.alter_column('vibration_level',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=2),
               existing_nullable=False)

    # ### end Alembic commands ###
