"""Implemented Cascade

Revision ID: 3d6703043d05
Revises: 55c951f6c51b
Create Date: 2024-11-19 06:38:43.053348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d6703043d05'
down_revision = '55c951f6c51b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_generated', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.drop_column('report_generated')

    # ### end Alembic commands ###
