"""Change to simulatin data

Revision ID: 864cafd49d68
Revises: 02282dbd5252
Create Date: 2025-03-12 10:50:24.131368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '864cafd49d68'
down_revision = '02282dbd5252'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_voltage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('end_voltage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('voltage_drop', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('battery_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.drop_column('battery_status')
        batch_op.drop_column('voltage_drop')
        batch_op.drop_column('end_voltage')
        batch_op.drop_column('start_voltage')

    # ### end Alembic commands ###
