"""Updated sensor model and added new fields

Revision ID: a5c76365164d
Revises: 10ac884c8b18
Create Date: 2024-11-17 21:35:42.813311

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a5c76365164d'
down_revision = '10ac884c8b18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_frequency', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('current_intensity', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('current_timestamp', sa.DateTime(), nullable=True))
        batch_op.drop_column('intensity')
        batch_op.drop_column('frequency')
        batch_op.drop_column('vibration_level')
        batch_op.drop_column('duration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('vibration_level', mysql.VARCHAR(length=2), nullable=False))
        batch_op.add_column(sa.Column('frequency', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('intensity', mysql.FLOAT(), nullable=False))
        batch_op.drop_column('current_timestamp')
        batch_op.drop_column('current_intensity')
        batch_op.drop_column('current_frequency')

    # ### end Alembic commands ###
