"""Add duration to Simulation and real-time control fields to Control

Revision ID: e8ea94b1a90f
Revises: a5c76365164d
Create Date: 2024-11-19 01:04:48.065266

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e8ea94b1a90f'
down_revision = 'a5c76365164d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('controls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_frequency', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('current_intensity', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('current_duration', sa.Float(), nullable=False))
        batch_op.alter_column('vibration_level',
               existing_type=mysql.VARCHAR(length=2),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.drop_column('frequency')
        batch_op.drop_column('duration')
        batch_op.drop_column('intensity')

    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.drop_column('duration')

    with op.batch_alter_table('controls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intensity', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('duration', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('frequency', mysql.FLOAT(), nullable=False))
        batch_op.alter_column('vibration_level',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=2),
               existing_nullable=False)
        batch_op.drop_column('current_duration')
        batch_op.drop_column('current_intensity')
        batch_op.drop_column('current_frequency')

    # ### end Alembic commands ###
